openapi: 3.1.0
info:
  version: 1.0.0
  title: nodejs-hw-mongodb
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    REST API для керування контактами з підтримкою авторизації, пагінації, завантаження фото та документації OpenAPI.
tags:
  - name: Contacts
    description: Операції з контактами
  - name: Auth
    description: Операції авторизації
servers:
  - url: http://localhost:3000
  - url: #посилання на задеплоєний сайт
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{contactId}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{contactId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{contactId}/delete.yaml'
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer 